
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/backgroudsys?serverTimezone=GMT%2b8

server:
  port: 9090
mybatis:
  mapper-locations: classpath:mapper/*.xml


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
